name: mepartoymemondo
favicon: null
layout_spectrum: 0.014984391396865249
typography_spectrum: 0.41874005482532084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7364904265850782
  lightness: 0.8624519638251513
  saturation: 0.03217309922911227
  rhythmicContrast: 0.18174033355899155
purpose: []
