name: mepartoymemondo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41874005482532084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a76b7'
    - '#fbfeff'
    - '#b7dcf6'
    - '#85bada'
    - '#5398bf'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose: []
